export { Hero } from "./hero";
export { CompanyLogos } from "./company-logos";
export { HowItWorks } from "./how-it-works";
export { Comparison } from "./comparison";
export { Testimonials } from "./testimonials";
export { Features } from "./features";
export { Pricing } from "./pricing";
export { FAQ } from "./faq";
export { CTABanner } from "./cta-banner";
